/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import presenter.INuevoAnimalView;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Especie;
import model.Sector;
import model.Veterinario;
import presenter.NuevoAnimalPresenter;
import model.Zoologico;

/**
 *
 * @author au6usto
 */
public class NuevoAnimalView extends javax.swing.JFrame implements INuevoAnimalView {

  private NuevoAnimalPresenter nuevoAnimalPresenter;
  private MainView mainView;

  /**
   * Creates new form NuevoAnimalView
   */
  public NuevoAnimalView() {
    initComponents();
    nuevoAnimalPresenter = new NuevoAnimalPresenter(this, mainView);
    this.updateViewFromModel();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextFieldEdad = new javax.swing.JTextField();
    jTextFieldOrigen = new javax.swing.JTextField();
    jTextFieldPeso = new javax.swing.JTextField();
    jComboBoxEspecie = new javax.swing.JComboBox<>();
    jComboBoxVeterinario = new javax.swing.JComboBox<>();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jComboBoxSector = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTextFieldEdad.setText("Edad");
    jTextFieldEdad.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        jTextFieldEdadFocusGained(evt);
      }
    });

    jTextFieldOrigen.setText("Origen");
    jTextFieldOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        jTextFieldOrigenFocusGained(evt);
      }
    });
    jTextFieldOrigen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldOrigenActionPerformed(evt);
      }
    });

    jTextFieldPeso.setText("Peso");
    jTextFieldPeso.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        jTextFieldPesoFocusGained(evt);
      }
    });

    jComboBoxEspecie.setAutoscrolls(true);

    jButton1.setText("Agregar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Cancelar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Nuevo Animal");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldOrigen))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(222, 222, 222)
            .addComponent(jLabel1)
            .addGap(0, 234, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jComboBoxSector, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBoxVeterinario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBoxEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jComboBoxVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jComboBoxSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrigenActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrigenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.updateModelFromView();
   
      this.close();
    }//GEN-LAST:event_jButton1ActionPerformed

  private void jTextFieldPesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPesoFocusGained
    jTextFieldPeso.selectAll();
  }//GEN-LAST:event_jTextFieldPesoFocusGained

  private void jTextFieldOrigenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOrigenFocusGained
    jTextFieldOrigen.selectAll();
  }//GEN-LAST:event_jTextFieldOrigenFocusGained

  private void jTextFieldEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEdadFocusGained
    jTextFieldEdad.selectAll();
  }//GEN-LAST:event_jTextFieldEdadFocusGained


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JComboBox<Object> jComboBoxEspecie;
  private javax.swing.JComboBox<Object> jComboBoxSector;
  private javax.swing.JComboBox<Object> jComboBoxVeterinario;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField jTextFieldEdad;
  private javax.swing.JTextField jTextFieldOrigen;
  private javax.swing.JTextField jTextFieldPeso;
  // End of variables declaration//GEN-END:variables

  @Override
  public NuevoAnimalPresenter getPresenter() {
    return nuevoAnimalPresenter;
  }

  @Override
  public void setPresenter(NuevoAnimalPresenter nuevoAnimalPresenter) {
    this.nuevoAnimalPresenter = nuevoAnimalPresenter;
  }

  @Override
  public void updateModelFromView() {  
    nuevoAnimalPresenter.save(
            jComboBoxEspecie.getSelectedItem(),
            jTextFieldOrigen.getText(),
            Integer.parseInt(jTextFieldEdad.getText()),
            Double.parseDouble(jTextFieldPeso.getText()),
            jComboBoxVeterinario.getSelectedItem(),
            jComboBoxSector.getSelectedItem());
    JOptionPane.showMessageDialog(this, "Animal guardado correctamente");
  }

  @Override
  public void updateViewFromModel() {
   
    for (Especie especie : Zoologico.getEspecies()){
      jComboBoxEspecie.addItem(especie);
    }
    
    for (Sector sector : Zoologico.getSectores()){
      jComboBoxSector.addItem(sector);
    }
    
    for (Veterinario veterinario : Zoologico.getVeterinarios()){
      jComboBoxVeterinario.addItem(veterinario);
    }
  }

  @Override
  public void open() {
    setVisible(true);
    jTextFieldEdad.selectAll();
    jTextFieldEdad.requestFocus();
  }

  @Override
  public void close() {
    dispose();
  }
}
